### ISSUE TITLE
Unable to find "snowpack-app-template-preact-hmr-tailwind" in the npm registry.

### ISSUE THREAD

**Issue by markfirmware** [Mozart409/snowpack-app-template-preact-hmr-tailwind#1]
npx create-snowpack-app --template snowpack-app-template-preact-hmr-tailwind abc
    npx: installed 29 in 11.494s

    [ERROR] Unable to find "snowpack-app-template-preact-hmr-tailwind" in the npm registry.
    [ERROR] Cannot continue safely. Exiting...

**Comment by Mozart409** [comment]
Hi,

yeah I can publish this package to NPM

**Comment by Mozart409** [comment]
Hi, I added the package to npm, but the creators of snowpack @FredKSchott and @drwpow would need to integrate my template to the "create-snowpack-app". I will help in any way I can, but I think we need to include them or open an issue there.

At the moment you can clone the repo via 
```sh
git clone https://github.com/Mozart409/snowpack-app-template-preact-hmr-tailwind <YOUR-APPNAME>
```
and if you wish you can delete the ".git" folder you create a new repo.

I hope it helps 👍

**Comment by markfirmware** [comment]
Thank you very much! I will be able to test later today.

**Comment by markfirmware** [comment]
Thanks. It is there now.
