### ISSUE TITLE
verifyProjectTemplate - unexpected end of json

### ISSUE THREAD

**Issue by markfirmware** [Mozart409/snowpack-app-template-preact-hmr-tailwind#3]
https://github.com/snowpackjs/snowpack/discussions/1968

    npx create-snowpack-app --template snowpack-app-template-preact-hmr-tailwind app
    npx: installed 29 in 11.266s

    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at verifyProjectTemplate (/root/.npm/_npx/1982520/lib/node_modules/create-snowpack-app/createSnowpackApp.js:69:23)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    [ERROR] Cannot continue safely. Exiting...

**Comment by Mozart409** [comment]
is this still relevant or did it fix it now?

**Comment by markfirmware** [comment]
Still failing

**Comment by markfirmware** [comment]
It is ok with me if you close this, I am no longer participating. Maybe snowpack is, I do not know.

**Comment by Mozart409** [comment]
```sh
npx create-snowpack-app --template snowpack-app-template-preact-hmr-tailwind app
Need to install the following packages:
  create-snowpack-app
Ok to proceed? (y) y

  - Using template snowpack-app-template-preact-hmr-tailwind
  - Creating a new project in /home/amadeus/GitHub/test/app
  - Installing package dependencies. This might take a couple of minutes.


added 981 packages, and audited 982 packages in 22s

66 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

  - Initializing git repo.

  - Success!
  - 
```


It works now...
